apiVersion: v1
kind: Secret
metadata:
  name: aws-secret
  namespace: default
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICI4OTEzNzczNjA4NzguZGtyLmVjci5jYS1jZW50cmFsLTEuYW1hem9uYXdzLmNvbSI6IHsKICAgICAgInVzZXJuYW1lIjogIkFXUyIsCiAgICAgICJwYXNzd29yZCI6ICJHMExPMHgwbnFPUGdqYVJmMkxXdU53ZFRrMUhOamNsdUpWMks0ZmpRT0dGIiwKICAgICAgImVtYWlsIjogImJhbnhhdHRpbGFAbWFpbC5jb20iCiAgICB9CiAgfQp9Cg==
