apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  labels:
    app: backend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      imagePullSecrets:
        - name: aws-secret
      containers:
        - name: backend
          image: 891377360878.dkr.ecr.ca-central-1.amazonaws.com/mernflix/backend
          resources:
            requests:
              cpu: 250m
              memory: 200Mi
            limits:
              cpu: 500m
              memory: 500Mi
          env:
            - name: MONGO_URL
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: mongodb-connection
            - name: TMDB_API_KEY
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: tmdb-key
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: backend-secret
                  key: jwt-secret
          ports:
            - containerPort: 5000
---
# https://kubernetes.io/docs/concepts/services-networking/service/
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: default
spec:
  selector:
    app: backend
  type: NodePort
  ports:
    - name: backend-service
      protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30001
---

