apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: default
type: Opaque
data:
  mongodb-connection: connection-string-in-base-64
  tmdb-key: connection-string-in-base-64
  jwt-secret: connection-string-in-base-64
